[package]
name = "starboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twilight-gateway = "0.11.0"
twilight-http = "0.11.0"
twilight-model = "0.11.2"
twilight-util = { version = "0.11.0", features = ["builder"] }
twilight-interactions = "0.11.0"
twilight-error = "0.11.4"
twilight-mention = "0.11.0"
twilight-standby = "0.11.0"

async-trait = "0.1.56"
tokio = { version = "1.19.2", features = ["full"] }
futures = "0.3.21"
dotenv = "0.15.0"
anyhow = "1.0.58"
sqlx = { version = "0.6.0", features = ["macros", "postgres", "offline", "runtime-tokio-rustls", "chrono", "json"]}
chrono = "0.4.19"
serde_json = "1.0"
serde = "1.0.137"
emojis = "0.4.0"
dashmap = "5.3.4"
moka = { version = "0.9.0", features = ["future"] }
